services:
  app:
    build: .
    container_name: trial-rails8
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    working_dir: /app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db
  db:
    container_name: trial-postgresql17
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rails
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  bundle: